# Generated by Django 3.0 on 2020-09-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterPart',
            fields=[
                ('part_id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.TextField(verbose_name='Customer Code')),
                ('project_code', models.TextField(verbose_name='Project Code')),
                ('supplier_code', models.TextField(verbose_name='Supplier Code')),
                ('part_no', models.TextField(verbose_name='Part No')),
                ('part_name', models.TextField(blank=True, verbose_name='Part Name')),
                ('snp', models.IntegerField(blank=True, verbose_name='Snp')),
                ('image', models.TextField(blank=True, verbose_name='Image')),
                ('status', models.TextField(verbose_name='Status')),
                ('model', models.TextField(verbose_name='Model')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('updated_by', models.TextField(verbose_name='Updated By')),
                ('updated_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Updated Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('number_of_comments', models.IntegerField()),
                ('number_of_pingbacks', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('authors', models.ManyToManyField(to='blog.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
